# Generated by Django 4.0.5 on 2022-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lek', '0002_rename_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consultas'], [1, 'Sugerencias'], [2, 'Recuperacion'], [3, 'Agradecimientos']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
